from Simulation import Simulation
from Simulation import Simulation
from GraphsPlot import drawVelocity, drawLocation

print("**** Sim of 1 entity and the rest attr are default ****")
sim = Simulation(1)
sim.simulate()
print("Positions:")
print(len(sim.entities_pos_at_k))
print(sim.entities_pos_at_k)
print("Desired Velocities of each entity:")
print(sim.desired_v_list)
print("Velocities:")
print(len(sim.entities_v_at_k))
print(sim.entities_v_at_k)
print()

print("**** Sim of 1 entity and random positions and desired velocities ****")
sim = Simulation(1, starting_pos="random", velocities_type="random")
sim.simulate()
print("Positions:")
print(len(sim.entities_pos_at_k))
print(sim.entities_pos_at_k)
print("Desired Velocities of each entity:")
print(sim.desired_v_list)
print("Velocities:")
print(len(sim.entities_v_at_k))
print(sim.entities_v_at_k)
print()

print("**** Sim of 3 entities and random positions and desired velocities ****")
print("$$$$$ WITHOUT CHECKING COLLISIONS $$$$$")
sim = Simulation(5, starting_pos="random", velocities_type="random")
sim.simulate()
print("Positions:")
print(len(sim.entities_pos_at_k))
print(sim.entities_pos_at_k)
print("Desired Velocities of each entity:")
print(sim.desired_v_list)
print("Velocities:")
print(len(sim.entities_v_at_k))
print(sim.entities_v_at_k)
drawVelocity(sim.entities_v_at_k, sim.entities_num)
drawLocation(sim.entities_pos_at_k, sim.entities_num)
